### ISSUE TITLE
IntelliClor control

### ISSUE THREAD

**Issue by bwoodworth** [bwoodworth/hassio-addons#12]
Thanks @parnic and @bwoodworth ... Really great work.

I did look in the library and tried setting up HA according to the state values I found:
  - platform: mqtt
    name: "Pool Salt Status"
    state_topic: pentair/status/state

  - platform: mqtt
    name: "Pool Salt Level 1"
    state_topic: pentair/level1/state

  - platform: mqtt
    name: "Pool Salt Level 2"
    state_topic: pentair/level2/state

  - platform: mqtt
    name: "Pool Salt Superchlorinator"
    state_topic: pentair/level1/state    
    
  - platform: mqtt
    name: "Pool Salt ppm"
    unit_of_measurement: 'ppm'
    state_topic: pentair/saltppm/state    

I am just now realizing that some of these values would need to go into the switch section, not the sensor section (e.g. the salt levels)...

I will wait for the next release.

@bwoodworth : I also have an IC40 chlorinator and a Variflow pump which I can switch to a Varispeed pump. so if you need any data or want me to test something, just let me know :-)

_Originally posted by @sarahmva in https://github.com/bwoodworth/hassio-addons/issues/9#issuecomment-658402593_

**Comment by bwoodworth** [comment]
Can you explain a little more about what you are trying to do?  There are already some readings coming into the addon like salt ppm.  Are there other values you need to be able to pull in as sensors?  Are there settings in the IntelliChlor that you need to be able to set?

**Comment by bwoodworth** [comment]
I think I see what you want and it should be doable in the current version of the library.  I will get something in there soon and you can test.

**Comment by sarahmva** [comment]
![D0CCE5D4-F308-4F7B-8BDB-1DAF53E3791B](https://user-images.githubusercontent.com/68161487/87476965-4bf18400-c5f5-11ea-9446-e143f35e0b7e.png)

This is a screenshot of the ScreenLogic App for the chlorinator.

Level1 and 2 would be the Pool and Spa output. Status I assume is operating status and the Superchlorination is an option to run the cell on 100% for 24 hours (never used it, I just shock the pool).

My preference would be to be able to set the output levels. I am sure others would also like the super option.

**Comment by bwoodworth** [comment]
In new release v1.21.  Please test

**Comment by sarahmva** [comment]
Unfortunately, the Chlorinator shows all "unkown" for the new values.

I also need to figure out what to add to the configuration to be able to control the salt cell. I need to find a good tool to look into mqtt and the different topics there. 

![image](https://user-images.githubusercontent.com/68161487/87638512-e6df8080-c711-11ea-89a2-47b0c0bd11f6.png)

**Comment by bwoodworth** [comment]
What does your HA configuration look like?

**Comment by bwoodworth** [comment]
Looks like you got it working from the other thread.  Closing.

**Comment by jefframsey0** [comment]
Not sure if the set salt levels are working right. I am trying to send the value for the pool setting increasing it to 70% from the existing 60 as a test. See anything wrong in my test config? I sent the mqtt message manually and via this test config in hassio.

Error from addon logs:

TypeError: this.setSaltCellConfig is not a function
    at UnitConnection.<anonymous> (/node_modules/node-screenlogic/set_salt:14:12)
    at UnitConnection.emit (events.js:315:20)
    at UnitConnection.onClientMessage (/node_modules/node-screenlogic/index.js:315:14)
    at Socket.<anonymous> (/node_modules/node-screenlogic/index.js:155:15)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
/node_modules/node-screenlogic/set_salt:14
      this.setSaltCellConfig(0, level, isNaN);
           ^
TypeError: this.setSaltCellConfig is not a function
    at UnitConnection.<anonymous> (/node_modules/node-screenlogic/set_salt:14:12)
    at UnitConnection.emit (events.js:315:20)
    at UnitConnection.onClientMessage (/node_modules/node-screenlogic/index.js:315:14)
    at Socket.<anonymous> (/node_modules/node-screenlogic/index.js:155:15)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)

My config:

switch:
  - platform: mqtt
    name: Pool Salt - Cell Setting
    command_topic: pentair/salt/pool/set
    state_topic: pentair/saltcelllevel1/state
    payload_off: 0
    state_off: 0
    payload_on: 70
    state_on: 70

MQTT state
![image](https://user-images.githubusercontent.com/67827002/87745449-eac7dd00-c7bb-11ea-90c1-9da4ed5545ff.png)

**Comment by bwoodworth** [comment]
Interesting. Have you done a rebuild of the add-on since updating to 1.21?

**Comment by jefframsey0** [comment]
Yep, saw the comments about the pump info so did post update.

**Comment by sarahmva** [comment]
Wow... what is that cool MQTT interface? I am still looking for something usable.

(Sorry @bwoodworth for hijacking this thread.)

**Comment by jefframsey0** [comment]
> Wow... what is that cool MQTT interface? I am still looking for something usable.
> 
> (Sorry @bwoodworth for hijacking this thread.)

Its pretty decent... heres a link https://www.microsoft.com/en-us/p/mqtt-explorer/9pp8sfm082wd?activetab=pivot:overviewtab

**Comment by bwoodworth** [comment]
I fixed the bug. Please test v1.22

**Comment by sarahmva** [comment]
Thank you so much. Unfortunately, HA does not (yet) show the update...

**Comment by bwoodworth** [comment]
Can you restart the addon and check the log for salt cell level 1 and 2?  Do they match what you tried to set it to?

**Comment by sarahmva** [comment]
> Can you restart the addon and check the log for salt cell level 1 and 2? Do they match what you tried to set it to?

Ah, sorry for the misunderstanding. For version 1.21 I could update it from the Add-on store. 1.22 is not yet available. there. Should I update manually?

**Comment by bwoodworth** [comment]
On the Add-On Store page you can reload to get the latest versions, but wait a minute.  The fix I made won't work.  I am working on another one.

**Comment by bwoodworth** [comment]
v1.23 released and should fix the issue.

**Comment by sarahmva** [comment]
Fantastic.... And it works :-) I could change the Values in HA and see them change in my Pentair App... Now I just need to find a way to change the units in climate control... Or use something else... 

![image](https://user-images.githubusercontent.com/68161487/87834855-7cd1f300-c859-11ea-8109-273d8cc64a9c.png)

**Comment by bwoodworth** [comment]
put this in your mqtt device config:

unit_of_measurement: '%'

**Comment by jefframsey0** [comment]
working great, thanks!

**Comment by jefframsey0** [comment]
> Can you restart the addon and check the log for salt cell level 1 and 2? Do they match what you tried to set it to?

tested both levels and everything is working perfectly

**Comment by bwoodworth** [comment]
Fantastic!  Closing.
